apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
# kind: ClusterRole // apply role in the entire cluster
metadata:
  name: server-read
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps/v1"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
# kind: ClusterRoleBinding // apply the roles in the entire cluster
metadata:
  name: server-read-bind
subjects:
  - kind: ServiceAccount
    name: server
    namespace: prod
roleRef:
  kind: Role
  # kind: ClusterRole
  name: server-read
  apiGroup: rbac.authorization.k8s.io